export const categories = [
    'Development',
    'Business',
    'Finance & Accounting',
    'IT & Software',
    'Office Productivity',
    'Personal Development',
    'Design',
    'Marketing',
    'Lifestyle',
    'Photography & Video',
    'Health & Fitness',
    'Music',
    'Teaching & Academics',
]
export const objectivePlacehoders = [
    'Go from a total beginner to a confident Python programmer',
    'Create 10 real-world Python programs (no toy programs)',
    'Strengthen your skills with bonus practice activities throughout the course',
    'Create an English Thesaurus app that returns definitions of English words',
    'Create a personal website entirely in Python',
    'Create a mobile app that improves your mood',
    'Create a portfolio website and publish it on a real server',
    'Create a desktop app for storing data for books',
    'Create a webcam app that detects moving objects',
    'Create a web scraper that extracts real-estate data',
    'Create a data visualization app',
    'Create a database app',
    'Create a geocoding web app',
    'Send automated emails',
    'Analyze and visualize data',
    'Use Python to schedule programs based on computer events.',
    'Learn OOP (Object-Oriented Programming)',
    'Learn GUIs (Graphical-User Interfaces)',
]
export const requirementsPlacehoders = [
    'Those with no prior knowledge of Python but want to learn Python.',
    'Those who know Python basics and want to master Python',
]
